spring:
  application:
    name: create-user-app-spring-jdbc
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

server:
  port: 8083